## Required config files ##
sample_sheet: "./config/samples.json"
recombination: False

## Reference genome path ##
### MUST BE UNCOMPRESSED (blame genmap, not me) ###
genome_paths: 
  dmel: "data/dmel.fna"
  wmel: "data/wmel.fna"
  wri: "data/wri.fna"

## Host and infection accessions ##
genome_contigs_for_depth_calculation:
  ## Each key is a group that mean cov will be calculated for. 
  ## Value should be the contig names in the reference genome. Must be list of strings.
  dmel: ["dmel_chrom"]
  wri: ["wri_chrom"]
  wmel: ["wmel_chrom"]
  ## You can add as many genomes as you would like

## Roles to define host and symbiont relationships. Only one host is allowed.
roles:
  hosts: "dmel"
  symbionts: ["wmel","wri"]
  

## mappability options ##
mappability:
  e_vals: [0]
  kmer_size: 150
  mismatches: 0
  score_cutoff: 1

## BAM filtering options ##
filter_bam:
  min_mapq: 20